baseurl = "http://soulcoder.me"
title = "Soul Coder"
languageCode = "zh-cn"
disqusShortname = "keviswang"
copyright = "Copyright (c) 2008 - 2014, Kevis Wang; all rights reserved."
MetaDataFormat = "yaml"

[author]
    name = "Kevis Wang"

[indexes]
    tag = "tags"
    topic = "topics"